"""
Interactive first-run setup wizard.
Detects missing credentials and walks the user through providing them.
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

ENV_FILE = Path(".env")

STEPS = [
    {
        "key": "TELEGRAM_BOT_TOKEN",
        "label": "Telegram Bot Token",
        "instructions": (
            "  1. Open Telegram and search for @BotFather\n"
            "  2. Send /newbot and follow the prompts to name your bot\n"
            "  3. BotFather will give you a token that looks like:\n"
            "     123456789:ABCdefGhIJKlmNoPQRsTUVwxyZ\n"
            "  4. Paste it below."
        ),
    },
    {
        "key": "TELEGRAM_CHAT_ID",
        "label": "Your Telegram Chat ID",
        "instructions": (
            "  1. Open Telegram and search for @userinfobot\n"
            "  2. Send it any message (e.g. /start)\n"
            "  3. It will reply with your numeric ID, e.g. 123456789\n"
            "  4. Paste it below."
        ),
    },
    {
        "key": "TICKETMASTER_API_KEY",
        "label": "Ticketmaster Discovery API Key",
        "instructions": (
            "  1. Go to https://developer.ticketmaster.com/\n"
            "  2. Click 'Get Your API Key' and create a free account\n"
            "  3. After signing in, go to 'My Apps' → create a new app\n"
            "  4. Your Consumer Key is your API key — paste it below."
        ),
    },
    {
        "key": "BANDSINTOWN_APP_ID",
        "label": "Bandsintown App ID",
        "instructions": (
            "  The Bandsintown API just needs any app identifier string.\n"
            "  You can use your name, email, or any short phrase.\n"
            "  Example: jane_concert_bot\n"
            "  Paste your chosen app ID below."
        ),
    },
]


def _read_existing_env() -> dict:
    values = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                values[k.strip()] = v.strip().strip('"').strip("'")
    return values


def _write_env(values: dict) -> None:
    lines = [
        "# Concert Bot — auto-generated by setup wizard",
        "",
    ]
    for k, v in values.items():
        lines.append(f'{k}="{v}"')
    lines += [
        "",
        'DIGEST_HOUR="9"',
        'DIGEST_MINUTE="0"',
        'TIMEZONE="Europe/London"',
        'DB_PATH="concerts.db"',
    ]
    ENV_FILE.write_text("\n".join(lines) + "\n")


def _missing_keys(existing: dict) -> list:
    required = [s["key"] for s in STEPS]
    return [k for k in required if not existing.get(k)]


def _banner(text: str) -> None:
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60)


def run_wizard() -> bool:
    """
    Returns True if setup is complete (either already was, or just finished).
    Returns False if the user quit early.
    """
    existing = _read_existing_env()
    missing = _missing_keys(existing)

    if not missing:
        return True

    _banner("Concert Bot — First-Run Setup")
    print(
        "\nWelcome! Before the bot can run, it needs a few credentials.\n"
        "This wizard will walk you through each one.\n"
        "Your answers are saved to a local .env file on your computer —\n"
        "they are never sent anywhere else.\n"
    )
    print(f"Missing credentials: {', '.join(missing)}\n")

    for step in STEPS:
        if step["key"] not in missing:
            continue

        print(f"\n--- {step['label']} ---")
        print(step["instructions"])
        print()

        while True:
            try:
                value = input(f"  Enter your {step['label']}: ").strip()
            except (KeyboardInterrupt, EOFError):
                print("\n\nSetup cancelled. Run 'python main.py' again to continue.")
                return False

            if value:
                existing[step["key"]] = value
                break
            print("  (Value cannot be empty — please try again.)")

    _write_env(existing)
    _banner("Setup complete!")
    print("\nYour credentials have been saved to .env\n")

    # Offer a test message now that credentials are saved
    try:
        answer = input("Would you like to send a test message to Telegram now to check it's working? (yes/no): ").strip().lower()
        if answer in ("yes", "y"):
            load_dotenv(ENV_FILE, override=True)
            from bot import send_test_message
            print("\nSending test message...")
            ok = send_test_message()
            if ok:
                print("✅ Test message sent! Check your Telegram — you should see a message from your bot.")
            else:
                print(
                    "❌ Test message failed. Don't worry — your credentials are saved.\n"
                    "   Double-check your bot token and chat ID, then run:\n"
                    "   python main.py --test"
                )
        else:
            print(
                "Skipped. You can send a test message any time by running:\n"
                "   python main.py --test"
            )
    except (KeyboardInterrupt, EOFError):
        pass

    print()
    return True


def check_env_or_setup() -> bool:
    """
    Call this at the top of main.py.
    Returns True when all credentials are present and the bot can start.
    """
    existing = _read_existing_env()
    missing = _missing_keys(existing)
    if missing:
        print("\n[Concert Bot] Missing credentials detected — launching setup wizard...\n")
        return run_wizard()
    return True
